"""Renault Twizy specific metrics for OVMS integration."""

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)
from homeassistant.components.binary_sensor import (
    BinarySensorDeviceClass,
)
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfLength,
    UnitOfPower,
    UnitOfSpeed,
    UnitOfTemperature,
    UnitOfTime,
    EntityCategory,
)

# Custom unit constants
UNIT_AMPERE_HOUR = "Ah"

# Renault Twizy specific metrics
RENAULT_TWIZY_METRICS = {
    # Battery metrics
    "xrt.b.energy.avail": {
        "name": "Renault Twizy Available Energy",
        "description": "Available energy in battery",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "renault_twizy",
    },
    "xrt.b.energy.full": {
        "name": "Renault Twizy Total Energy",
        "description": "Total energy capacity of battery",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY_STORAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "renault_twizy",
    },
    "xrt.b.u.soc.max": {
        "name": "Renault Twizy SOC Maximum",
        "description": "Maximum state of charge",
        "icon": "mdi:battery-high",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "renault_twizy",
    },
    "xrt.b.u.soc.min": {
        "name": "Renault Twizy SOC Minimum",
        "description": "Minimum state of charge",
        "icon": "mdi:battery-low",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "renault_twizy",
    },
    "xrt.b.u.temp.max": {
        "name": "Renault Twizy Battery Temp Maximum",
        "description": "Maximum battery temperature",
        "icon": "mdi:thermometer-high",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "renault_twizy",
    },
    "xrt.b.u.temp.min": {
        "name": "Renault Twizy Battery Temp Minimum",
        "description": "Minimum battery temperature",
        "icon": "mdi:thermometer-low",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "renault_twizy",
    },
    "xrt.b.u.volt.max": {
        "name": "Renault Twizy Battery Voltage Maximum",
        "description": "Maximum battery voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "suggested_display_precision": 2,
        "category": "renault_twizy",
    },
    "xrt.b.u.volt.min": {
        "name": "Renault Twizy Battery Voltage Minimum",
        "description": "Minimum battery voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "suggested_display_precision": 2,
        "category": "renault_twizy",
    },

    # BMS metrics
    "xrt.bms.balancetime": {
        "name": "Renault Twizy BMS Balance Time",
        "description": "Battery balancing time",
        "icon": "mdi:battery-sync",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTime.SECONDS,
        "category": "renault_twizy",
    },
    "xrt.bms.balancing": {
        "name": "Renault Twizy BMS Balancing",
        "description": "Battery balancing active",
        "icon": "mdi:battery-sync",
        "device_class": BinarySensorDeviceClass.RUNNING,
        "category": "renault_twizy",
    },
    "xrt.bms.error": {
        "name": "Renault Twizy BMS Error",
        "description": "BMS error code",
        "icon": "mdi:alert-circle",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "xrt.bms.state1": {
        "name": "Renault Twizy BMS State 1",
        "description": "BMS state parameter 1",
        "icon": "mdi:information",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "xrt.bms.state2": {
        "name": "Renault Twizy BMS State 2",
        "description": "BMS state parameter 2",
        "icon": "mdi:information",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "xrt.bms.temp": {
        "name": "Renault Twizy BMS Temperature",
        "description": "BMS temperature",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "renault_twizy",
    },
    "xrt.bms.type": {
        "name": "Renault Twizy BMS Type",
        "description": "BMS type identifier",
        "icon": "mdi:identifier",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },

    # Configuration metrics
    "xrt.cfg.applied": {
        "name": "Renault Twizy Config Applied",
        "description": "Configuration applied status",
        "icon": "mdi:check-circle",
        "device_class": BinarySensorDeviceClass.CONNECTIVITY,
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "xrt.cfg.base": {
        "name": "Renault Twizy Config Base",
        "description": "Configuration base parameter",
        "icon": "mdi:tune",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "xrt.cfg.profile": {
        "name": "Renault Twizy Config Profile",
        "description": "Configuration profile parameters",
        "icon": "mdi:tune-vertical",
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "xrt.cfg.type": {
        "name": "Renault Twizy Config Type",
        "description": "Configuration vehicle type",
        "icon": "mdi:car-electric",
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "xrt.cfg.unsaved": {
        "name": "Renault Twizy Config Unsaved",
        "description": "Unsaved configuration changes",
        "icon": "mdi:content-save-alert",
        "device_class": BinarySensorDeviceClass.PROBLEM,
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "xrt.cfg.user": {
        "name": "Renault Twizy Config User",
        "description": "User configuration parameter",
        "icon": "mdi:account-cog",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "xrt.cfg.ws": {
        "name": "Renault Twizy Config WS",
        "description": "WS configuration parameter",
        "icon": "mdi:tune",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },

    # Inverter metrics
    "xrt.i.cur.act": {
        "name": "Renault Twizy Inverter Current",
        "description": "Inverter actual current",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "renault_twizy",
    },
    "xrt.i.frq.output": {
        "name": "Renault Twizy Inverter Frequency",
        "description": "Inverter output frequency",
        "icon": "mdi:sine-wave",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
    },
    "xrt.i.frq.slip": {
        "name": "Renault Twizy Inverter Slip",
        "description": "Inverter slip frequency",
        "icon": "mdi:sine-wave",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
    },
    "xrt.i.pwr.act": {
        "name": "Renault Twizy Inverter Power",
        "description": "Inverter actual power",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPower.KILO_WATT,
        "category": "renault_twizy",
    },
    "xrt.i.trq.act": {
        "name": "Renault Twizy Actual Torque",
        "description": "Actual motor torque",
        "icon": "mdi:gauge",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
    },
    "xrt.i.trq.demand": {
        "name": "Renault Twizy Torque Demand",
        "description": "Demanded motor torque",
        "icon": "mdi:gauge",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
    },
    "xrt.i.trq.limit": {
        "name": "Renault Twizy Torque Limit",
        "description": "Motor torque limit",
        "icon": "mdi:gauge",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
    },
    "xrt.i.vlt.act": {
        "name": "Renault Twizy Inverter Voltage",
        "description": "Inverter actual voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "suggested_display_precision": 2,
        "category": "renault_twizy",
    },
    "xrt.i.vlt.bat": {
        "name": "Renault Twizy Inverter Battery Voltage",
        "description": "Inverter battery voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "suggested_display_precision": 2,
        "category": "renault_twizy",
    },
    "xrt.i.vlt.cap": {
        "name": "Renault Twizy Inverter Cap",
        "description": "Inverter capacitor current",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "renault_twizy",
    },
    "xrt.i.vlt.mod": {
        "name": "Renault Twizy Voltage Modulation",
        "description": "Inverter voltage modulation",
        "icon": "mdi:sine-wave",
        "device_class": SensorDeviceClass.POWER_FACTOR,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "renault_twizy",
    },

    # Module version
    "xrt.m.version": {
        "name": "Renault Twizy Module Version",
        "description": "Twizy module software version",
        "icon": "mdi:tag-text",
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },

    # Vehicle statistics
    "xrt.p.stats.acc.dist": {
        "name": "Renault Twizy Acceleration Distance",
        "description": "Distance covered during acceleration",
        "icon": "mdi:map-marker-distance",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfLength.KILOMETERS,
        "category": "renault_twizy",
    },
    "xrt.p.stats.acc.recd": {
        "name": "Renault Twizy Acceleration Energy Recovered",
        "description": "Energy recovered during acceleration",
        "icon": "mdi:battery-plus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "renault_twizy",
    },
    "xrt.p.stats.acc.spdavg": {
        "name": "Renault Twizy Average Acceleration",
        "description": "Average acceleration speed",
        "icon": "mdi:speedometer",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfSpeed.KILOMETERS_PER_HOUR + "/s",
        "category": "renault_twizy",
    },
    "xrt.p.stats.acc.used": {
        "name": "Renault Twizy Acceleration Energy Used",
        "description": "Energy used during acceleration",
        "icon": "mdi:battery-minus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "renault_twizy",
    },
    "xrt.p.stats.cst.dist": {
        "name": "Renault Twizy Constant Speed Distance",
        "description": "Distance covered at constant speed",
        "icon": "mdi:map-marker-distance",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfLength.KILOMETERS,
        "category": "renault_twizy",
    },
    "xrt.p.stats.cst.recd": {
        "name": "Renault Twizy Constant Speed Energy Recovered",
        "description": "Energy recovered at constant speed",
        "icon": "mdi:battery-plus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "renault_twizy",
    },
    "xrt.p.stats.cst.spdavg": {
        "name": "Renault Twizy Average Speed",
        "description": "Average constant speed",
        "icon": "mdi:speedometer",
        "device_class": SensorDeviceClass.SPEED,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfSpeed.KILOMETERS_PER_HOUR,
        "category": "renault_twizy",
    },
    "xrt.p.stats.cst.used": {
        "name": "Renault Twizy Constant Speed Energy Used",
        "description": "Energy used at constant speed",
        "icon": "mdi:battery-minus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "renault_twizy",
    },
    "xrt.p.stats.dec.dist": {
        "name": "Renault Twizy Deceleration Distance",
        "description": "Distance covered during deceleration",
        "icon": "mdi:map-marker-distance",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfLength.KILOMETERS,
        "category": "renault_twizy",
    },
    "xrt.p.stats.dec.recd": {
        "name": "Renault Twizy Deceleration Energy Recovered",
        "description": "Energy recovered during deceleration",
        "icon": "mdi:battery-plus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "renault_twizy",
    },
    "xrt.p.stats.dec.spdavg": {
        "name": "Renault Twizy Average Deceleration",
        "description": "Average deceleration speed",
        "icon": "mdi:speedometer",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfSpeed.KILOMETERS_PER_HOUR + "/s",
        "category": "renault_twizy",
    },
    "xrt.p.stats.dec.used": {
        "name": "Renault Twizy Deceleration Energy Used",
        "description": "Energy used during deceleration",
        "icon": "mdi:battery-minus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "renault_twizy",
    },
    "xrt.p.stats.ldn.dist": {
        "name": "Renault Twizy Downhill Distance",
        "description": "Distance covered going downhill",
        "icon": "mdi:map-marker-distance",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfLength.KILOMETERS,
        "category": "renault_twizy",
    },
    "xrt.p.stats.ldn.hsum": {
        "name": "Renault Twizy Downhill Elevation",
        "description": "Total downhill elevation",
        "icon": "mdi:elevation-decline",
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfLength.METERS,
        "category": "renault_twizy",
    },
    "xrt.p.stats.ldn.recd": {
        "name": "Renault Twizy Downhill Energy Recovered",
        "description": "Energy recovered going downhill",
        "icon": "mdi:battery-plus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "renault_twizy",
    },
    "xrt.p.stats.ldn.used": {
        "name": "Renault Twizy Downhill Energy Used",
        "description": "Energy used going downhill",
        "icon": "mdi:battery-minus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "renault_twizy",
    },
    "xrt.p.stats.lup.dist": {
        "name": "Renault Twizy Uphill Distance",
        "description": "Distance covered going uphill",
        "icon": "mdi:map-marker-distance",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfLength.KILOMETERS,
        "category": "renault_twizy",
    },
    "xrt.p.stats.lup.hsum": {
        "name": "Renault Twizy Uphill Elevation",
        "description": "Total uphill elevation",
        "icon": "mdi:elevation-rise",
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfLength.METERS,
        "category": "renault_twizy",
    },
    "xrt.p.stats.lup.recd": {
        "name": "Renault Twizy Uphill Energy Recovered",
        "description": "Energy recovered going uphill",
        "icon": "mdi:battery-plus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "renault_twizy",
    },
    "xrt.p.stats.lup.used": {
        "name": "Renault Twizy Uphill Energy Used",
        "description": "Energy used going uphill",
        "icon": "mdi:battery-minus",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "renault_twizy",
    },

    # Scale metrics
    "xrt.s.b.pwr.drv": {
        "name": "Renault Twizy Battery Power Drive Scale",
        "description": "Battery drive power scale factor",
        "icon": "mdi:scale-balance",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
    },
    "xrt.s.b.pwr.rec": {
        "name": "Renault Twizy Battery Power Recovery Scale",
        "description": "Battery recovery power scale factor",
        "icon": "mdi:scale-balance",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
    },
    "xrt.s.m.trq.drv": {
        "name": "Renault Twizy Motor Torque Drive Scale",
        "description": "Motor drive torque scale factor",
        "icon": "mdi:scale-balance",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
    },
    "xrt.s.m.trq.rec": {
        "name": "Renault Twizy Motor Torque Recovery Scale",
        "description": "Motor recovery torque scale factor",
        "icon": "mdi:scale-balance",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
    },

    # Vehicle alerts and status
    "xrt.v.b.alert.12v": {
        "name": "Renault Twizy 12V Alert",
        "description": "12V battery alert",
        "icon": "mdi:car-battery",
        "device_class": BinarySensorDeviceClass.PROBLEM,
        "category": "renault_twizy",
    },
    "xrt.v.b.alert.batt": {
        "name": "Renault Twizy Battery Alert",
        "description": "Main battery alert",
        "icon": "mdi:battery-alert",
        "device_class": BinarySensorDeviceClass.PROBLEM,
        "category": "renault_twizy",
    },
    "xrt.v.b.alert.temp": {
        "name": "Renault Twizy Temperature Alert",
        "description": "Battery temperature alert",
        "icon": "mdi:thermometer-alert",
        "device_class": BinarySensorDeviceClass.PROBLEM,
        "category": "renault_twizy",
    },
    "xrt.v.b.status": {
        "name": "Renault Twizy Battery Status",
        "description": "Battery status code",
        "icon": "mdi:information",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "xrt.v.c.status": {
        "name": "Renault Twizy Charger Status",
        "description": "Charger status code",
        "icon": "mdi:information",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "xrt.v.e.locked.speed": {
        "name": "Renault Twizy Locked Speed",
        "description": "Speed when the vehicle was locked",
        "icon": "mdi:speedometer",
        "device_class": SensorDeviceClass.SPEED,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfSpeed.KILOMETERS_PER_HOUR,
        "category": "renault_twizy",
    },
    "xrt.v.e.valet.odo": {
        "name": "Renault Twizy Valet Odometer",
        "description": "Odometer reading when valet mode was activated",
        "icon": "mdi:car-key",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfLength.KILOMETERS,
        "category": "renault_twizy",
    },
    "xrt.v.i.status": {
        "name": "Renault Twizy Inverter Status",
        "description": "Inverter status code",
        "icon": "mdi:information",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "renault_twizy",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
}
