"""Smart ED specific metrics for OVMS integration."""

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)
from homeassistant.components.binary_sensor import (
    BinarySensorDeviceClass,
)
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfLength,
    UnitOfPower,
    UnitOfTemperature,
    UnitOfTime,
)

# Vehicle metadata
VEHICLE_TYPE = "smart_ed"
VEHICLE_NAME = "Smart ED"
# OVMS publishes Smart ED (Fortwo 451 Electric Drive) metrics under the "xse"
# prefix - every metric key below uses it, and const.VEHICLE_TOPIC_PREFIXES maps
# "xse" to this car. The prefix must match so config-flow discovery can
# auto-detect the vehicle; "xsq" is the newer Smart 453/EQ module and never
# matches these topics.
METRIC_PREFIX = "xse."

# Smart ED specific metrics
SMART_ED_METRICS = {
    # --- myBMS: high-voltage battery management ----------------------------
    "xse.mybms.amps2": {
        "name": "Smart ED Battery Current",
        "description": "Battery current read on CAN/BMS (Smart 451 ED).",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "smart_ed",
    },
    "xse.mybms.power": {
        "name": "Smart ED BMS Power",
        "description": "Battery power as voltage x current (Smart 451 ED).",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPower.KILO_WATT,
        "category": "smart_ed",
    },
    "xse.mybms.hv": {
        "name": "Smart ED High Voltage",
        "description": "Total voltage of the HV system (Smart 451 ED).",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "suggested_display_precision": 2,
        "category": "smart_ed",
    },
    "xse.mybms.adc.cvolts.min": {
        "name": "Smart ED Cell Voltage Min",
        "description": "Minimum cell voltage from BMS ADC (Smart 451 ED).",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.MILLIVOLT,
        "category": "smart_ed",
    },
    "xse.mybms.adc.cvolts.mean": {
        "name": "Smart ED Cell Voltage Mean",
        "description": "Mean cell voltage from BMS ADC (Smart 451 ED).",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.MILLIVOLT,
        "category": "smart_ed",
    },
    "xse.mybms.adc.cvolts.max": {
        "name": "Smart ED Cell Voltage Max",
        "description": "Maximum cell voltage from BMS ADC (Smart 451 ED).",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.MILLIVOLT,
        "category": "smart_ed",
    },
    "xse.mybms.adc.volts.offset": {
        "name": "Smart ED Cell Voltage Offset",
        "description": (
            "Calculated offset between raw cell voltages and ADC reference "
            "(Smart 451 ED, typically ~90 mV)."
        ),
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.MILLIVOLT,
        "category": "smart_ed",
    },
    "xse.mybms.isolation": {
        "name": "Smart ED Isolation Resistance",
        "description": "Isolation resistance in the DC path (Smart 451 ED).",
        "icon": "mdi:omega",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": "kOhm",
        "category": "smart_ed",
    },
    "xse.mybms.dc.fault": {
        "name": "Smart ED DC Isolation Fault",
        "description": "DC-isolation fault flag on the Smart 451 ED.",
        "icon": "mdi:alert",
        "device_class": BinarySensorDeviceClass.PROBLEM,
        "category": "smart_ed",
    },
    "xse.mybms.hv.contact.cycles.left": {
        "name": "Smart ED HV Contactor Cycles Left",
        "description": (
            "Remaining HV battery contactor switching cycles on the Smart "
            "451 ED; counts down toward the maximum."
        ),
        "icon": "mdi:counter",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": "cycles",
        "category": "smart_ed",
    },
    "xse.mybms.hv.contact.cycles.max": {
        "name": "Smart ED HV Contactor Cycles Max",
        "description": (
            "Maximum HV battery contactor switching cycles (Smart 451 ED, "
            "static design limit)."
        ),
        "icon": "mdi:counter",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": "cycles",
        "category": "smart_ed",
    },
    "xse.mybms.batt.vin": {
        "name": "Smart ED Battery VIN",
        "description": "Vehicle identification number stored in the BMS.",
        "icon": "mdi:identifier",
        "category": "smart_ed",
    },
    # --- Pack / cell capacity health (SOH telemetry) ----------------------
    "xse.v.b.c.capacity": {
        "name": "Smart ED Cell Capacity",
        "description": (
            "Per-cell capacity in ampere-seconds (As); the integration "
            "aggregates the cell vector into min/max/avg statistics "
            "(Smart 451 ED)."
        ),
        "icon": "mdi:battery-medium",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": "As",
        "category": "smart_ed",
    },
    "xse.v.b.real.soc": {
        "name": "Smart ED Real State of Charge",
        "description": "Real (BMS) state of charge (Smart 451 ED).",
        "icon": "mdi:battery",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "smart_ed",
    },
    "xse.cepc.battery.age.condition": {
        "name": "Smart ED Battery Age Condition",
        "description": "Battery age/condition estimate (Smart 451 ED).",
        "icon": "mdi:battery-heart-variant",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "smart_ed",
    },
    "xse.v.b.p.capacity.avg": {
        "name": "Smart ED Cell Capacity Average",
        "description": "Pack average cell capacity in ampere-seconds (As).",
        "icon": "mdi:battery-medium",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": "As",
        "category": "smart_ed",
    },
    "xse.v.b.p.capacity.min": {
        "name": "Smart ED Cell Capacity Min",
        "description": "Weakest cell capacity in the pack in As (Smart 451 ED).",
        "icon": "mdi:battery-low",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": "As",
        "category": "smart_ed",
    },
    "xse.v.b.p.capacity.max": {
        "name": "Smart ED Cell Capacity Max",
        "description": "Strongest cell capacity in the pack in As (Smart 451 ED).",
        "icon": "mdi:battery-high",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": "As",
        "category": "smart_ed",
    },
    "xse.v.b.p.capacity.min.cell": {
        "name": "Smart ED Weakest Cell Number",
        "description": "Index of the weakest cell in the pack (Smart 451 ED).",
        "icon": "mdi:numeric",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "smart_ed",
    },
    "xse.v.b.p.capacity.max.cell": {
        "name": "Smart ED Strongest Cell Number",
        "description": "Index of the strongest cell in the pack (Smart 451 ED).",
        "icon": "mdi:numeric",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "smart_ed",
    },
    "xse.v.b.p.capacity.stddev": {
        "name": "Smart ED Cell Capacity Std Dev",
        "description": "Current cell capacity standard deviation in As.",
        "icon": "mdi:sigma",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": "As",
        "category": "smart_ed",
    },
    "xse.v.b.p.voltage.min.cell": {
        "name": "Smart ED Lowest Voltage Cell Number",
        "description": "Index of the lowest-voltage cell in the pack.",
        "icon": "mdi:numeric",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "smart_ed",
    },
    "xse.v.b.p.voltage.max.cell": {
        "name": "Smart ED Highest Voltage Cell Number",
        "description": "Index of the highest-voltage cell in the pack.",
        "icon": "mdi:numeric",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "smart_ed",
    },
    "xse.v.b.p.last.meas.days": {
        "name": "Smart ED Days Since Capacity Measurement",
        "description": (
            "Days elapsed since the last successful BMS capacity measurement "
            "(Smart 451 ED)."
        ),
        "icon": "mdi:calendar-clock",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTime.DAYS,
        "category": "smart_ed",
    },
    "xse.v.b.p.hv.off.time": {
        "name": "Smart ED HV Contactor Off Time",
        "description": "High-voltage contactor off time (Smart 451 ED).",
        "icon": "mdi:timer-off",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTime.SECONDS,
        "category": "smart_ed",
    },
    "xse.v.b.p.hv.lowcurrent": {
        "name": "Smart ED HV Low Current Time",
        "description": (
            "Counter of time with no battery current, reset by heating or "
            "driving (Smart 451 ED)."
        ),
        "icon": "mdi:timer-sand",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTime.SECONDS,
        "category": "smart_ed",
    },
    "xse.v.b.p.ocv.timer": {
        "name": "Smart ED OCV Timer",
        "description": (
            "Time remaining until the pack reaches open-circuit-voltage "
            "state (Smart 451 ED)."
        ),
        "icon": "mdi:timer",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTime.SECONDS,
        "category": "smart_ed",
    },
    # --- 12V system & HV status -------------------------------------------
    "xse.v.b.12v.voltage": {
        "name": "Smart ED 12V Battery Voltage",
        "description": "Auxiliary 12V battery voltage (Smart 451 ED).",
        "icon": "mdi:car-battery",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "suggested_display_precision": 2,
        "category": "smart_ed",
    },
    "xse.hv.off.time": {
        "name": "Smart ED HV Off Time",
        "description": "Time the high-voltage system has been off (Smart 451 ED).",
        "icon": "mdi:timer-off",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTime.SECONDS,
        "category": "smart_ed",
    },
    "xse.v.b.hv.active": {
        "name": "Smart ED HV Battery Active",
        "description": "High-voltage battery active status (Smart 451 ED).",
        "icon": "mdi:flash",
        "device_class": BinarySensorDeviceClass.POWER,
        "category": "smart_ed",
    },
    "xse.v.bus.awake": {
        "name": "Smart ED Bus Awake",
        "description": "Vehicle CAN bus awake status (Smart 451 ED).",
        "icon": "mdi:power",
        "device_class": BinarySensorDeviceClass.POWER,
        "category": "smart_ed",
    },
    "xse.v.c.active": {
        "name": "Smart ED Charging Active",
        "description": "Charging active status (Smart 451 ED).",
        "icon": "mdi:battery-charging",
        "device_class": BinarySensorDeviceClass.BATTERY_CHARGING,
        "category": "smart_ed",
    },
    # --- Energy use & trip / odometer -------------------------------------
    "xse.v.b.energy.used.start": {
        "name": "Smart ED Energy Used Since Start",
        "description": "Dashboard energy used since trip start (Smart 451 ED).",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "smart_ed",
    },
    "xse.v.b.energy.used.reset": {
        "name": "Smart ED Energy Used Since Reset",
        "description": "Dashboard energy used since reset (Smart 451 ED).",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "smart_ed",
    },
    "xse.v.display.trip.start": {
        "name": "Smart ED Trip Distance Since Start",
        "description": "Dashboard trip distance since start (Smart 451 ED).",
        "icon": "mdi:map-marker-distance",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfLength.KILOMETERS,
        "category": "smart_ed",
    },
    "xse.v.display.trip.reset": {
        "name": "Smart ED Trip Distance Since Reset",
        "description": "Dashboard trip distance since reset (Smart 451 ED).",
        "icon": "mdi:map-marker-distance",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfLength.KILOMETERS,
        "category": "smart_ed",
    },
    "xse.v.pos.odometer.start": {
        "name": "Smart ED Odometer At Start",
        "description": "Odometer reading at last ignition-on (Smart 451 ED).",
        "icon": "mdi:counter",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfLength.KILOMETERS,
        "category": "smart_ed",
    },
    "xse.v.display.time": {
        "name": "Smart ED Dashboard Time",
        "description": "Dashboard clock time in minutes (Smart 451 ED).",
        "icon": "mdi:clock",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTime.MINUTES,
        "category": "smart_ed",
    },
    # --- Eco scores (dashboard driving feedback) --------------------------
    "xse.v.display.ecoscore": {
        "name": "Smart ED Eco Score",
        "description": "Overall eco score over the last 6 hours (Smart 451 ED).",
        "icon": "mdi:leaf",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "smart_ed",
    },
    "xse.v.display.accel": {
        "name": "Smart ED Eco Score Acceleration",
        "description": "Eco score for acceleration over the last 6 hours.",
        "icon": "mdi:leaf",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "smart_ed",
    },
    "xse.v.display.const": {
        "name": "Smart ED Eco Score Constant",
        "description": "Eco score for constant driving over the last 6 hours.",
        "icon": "mdi:leaf",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "smart_ed",
    },
    "xse.v.display.coast": {
        "name": "Smart ED Eco Score Coasting",
        "description": "Eco score for coasting over the last 6 hours.",
        "icon": "mdi:leaf",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "smart_ed",
    },
    # --- NLG6 / OBL on-board charger --------------------------------------
    "xse.v.nlg6.present": {
        "name": "Smart ED Charger Present",
        "description": "On-board charger (NLG6 or OBL) present (Smart 451 ED).",
        "icon": "mdi:ev-station",
        "device_class": BinarySensorDeviceClass.CONNECTIVITY,
        "category": "smart_ed",
    },
    "xse.v.nlg6.main.volts": {
        "name": "Smart ED Charger Mains Voltage",
        "description": "On-board charger mains phase voltages (Smart 451 ED).",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "suggested_display_precision": 2,
        "category": "smart_ed",
    },
    "xse.v.nlg6.main.amps": {
        "name": "Smart ED Charger Mains Current",
        "description": "On-board charger mains phase currents (Smart 451 ED).",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "smart_ed",
    },
    "xse.v.nlg6.amps.setpoint": {
        "name": "Smart ED Charger Current Setpoint",
        "description": "On-board charger current setpoint (Smart 451 ED).",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "smart_ed",
    },
    "xse.v.nlg6.amps.cablecode": {
        "name": "Smart ED Charger Cable Current",
        "description": "Charger current limit encoded by the cable.",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "smart_ed",
    },
    "xse.v.nlg6.amps.chargingpoint": {
        "name": "Smart ED Charging Point Current",
        "description": "Charging point (EVSE) available current (Smart 451 ED).",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "smart_ed",
    },
    "xse.v.nlg6.dc.current": {
        "name": "Smart ED Charger DC Current",
        "description": "On-board charger low-voltage DC current (Smart 451 ED).",
        "icon": "mdi:current-dc",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "smart_ed",
    },
    "xse.v.nlg6.dc.hv": {
        "name": "Smart ED Charger HV Voltage",
        "description": "On-board charger high-voltage output (Smart 451 ED).",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "suggested_display_precision": 2,
        "category": "smart_ed",
    },
    "xse.v.nlg6.dc.lv": {
        "name": "Smart ED Charger LV Voltage",
        "description": "On-board charger low-voltage (12V) output (Smart 451 ED).",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "suggested_display_precision": 2,
        "category": "smart_ed",
    },
    "xse.v.nlg6.temps": {
        "name": "Smart ED Charger Temperatures",
        "description": "On-board charger temperature readings (Smart 451 ED).",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "smart_ed",
    },
    "xse.v.nlg6.temp.reported": {
        "name": "Smart ED Charger Temperature Reported",
        "description": "On-board charger reported temperature (Smart 451 ED).",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "smart_ed",
    },
    "xse.v.nlg6.temp.socket": {
        "name": "Smart ED Charger Socket Temperature",
        "description": "On-board charger socket temperature (Smart 451 ED).",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "smart_ed",
    },
    "xse.v.nlg6.temp.coolingplate": {
        "name": "Smart ED Charger Cooling Plate Temperature",
        "description": "On-board charger cooling-plate temperature (Smart 451 ED).",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "smart_ed",
    },
    # --- CEPC: cooling, heating, vacuum subsystems ------------------------
    "xse.cepc.cooling.temp": {
        "name": "Smart ED Cooling Temperature",
        "description": "Battery cooling circuit temperature (Smart 451 ED).",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "smart_ed",
    },
    "xse.cepc.cooling.pump.temp": {
        "name": "Smart ED Cooling Pump Temperature",
        "description": "Cooling pump temperature (Smart 451 ED).",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "smart_ed",
    },
    "xse.cepc.cooling.pump.lv": {
        "name": "Smart ED Cooling Pump Voltage",
        "description": "Cooling pump supply voltage (Smart 451 ED).",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "suggested_display_precision": 2,
        "category": "smart_ed",
    },
    "xse.cepc.cooling.pump.amps": {
        "name": "Smart ED Cooling Pump Current",
        "description": "Cooling pump current draw (Smart 451 ED).",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "smart_ed",
    },
    "xse.cepc.cooling.pump.rpm": {
        "name": "Smart ED Cooling Pump Speed",
        "description": "Cooling pump speed as a percentage of maximum.",
        "icon": "mdi:pump",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "smart_ed",
    },
    "xse.cepc.cooling.pump.otr": {
        "name": "Smart ED Cooling Pump Operating Hours",
        "description": "Cooling pump cumulative operating hours (Smart 451 ED).",
        "icon": "mdi:timer-outline",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfTime.HOURS,
        "category": "smart_ed",
    },
    "xse.cepc.cooling.fan.rpm": {
        "name": "Smart ED Cooling Fan Speed",
        "description": "Cooling fan speed as a percentage of maximum.",
        "icon": "mdi:fan",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "smart_ed",
    },
    "xse.cepc.cooling.fan.otr": {
        "name": "Smart ED Cooling Fan Operating Hours",
        "description": "Cooling fan cumulative operating hours (Smart 451 ED).",
        "icon": "mdi:timer-outline",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfTime.HOURS,
        "category": "smart_ed",
    },
    "xse.cepc.battery.heater.on": {
        "name": "Smart ED Battery Heater Active",
        "description": "Battery heater active status (Smart 451 ED).",
        "icon": "mdi:radiator",
        "device_class": BinarySensorDeviceClass.HEAT,
        "category": "smart_ed",
    },
    "xse.cepc.battery.heater.otr": {
        "name": "Smart ED Battery Heater Operating Hours",
        "description": "Battery heater cumulative operating hours (Smart 451 ED).",
        "icon": "mdi:timer-outline",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfTime.HOURS,
        "category": "smart_ed",
    },
    "xse.cepc.vaccum.pump.otr": {
        "name": "Smart ED Vacuum Pump Operating Hours",
        "description": "Brake vacuum pump cumulative operating hours (Smart 451 ED).",
        "icon": "mdi:timer-outline",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfTime.HOURS,
        "category": "smart_ed",
    },
    "xse.cepc.wippen": {
        "name": "Smart ED Paddle Shifter",
        "description": "Steering-wheel recuperation paddle state (Smart 451 ED).",
        "icon": "mdi:gesture-tap-button",
        "device_class": BinarySensorDeviceClass.POWER,
        "category": "smart_ed",
    },
}
