"""Smart ForTwo specific metrics for OVMS integration."""

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)
from homeassistant.components.binary_sensor import (
    BinarySensorDeviceClass,
)
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfLength,
    UnitOfPower,
    UnitOfTemperature,
    UnitOfTime,
)
from homeassistant.helpers.entity import EntityCategory

# Smart ForTwo specific metrics
SMART_FORTWO_METRICS = {
    "xsq.bms.amp2": {
        "name": "Smart ForTwo BMS Amp2",
        "description": "BMS secondary amp measurement",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "smart_fortwo",
    },
    "xsq.bms.amps": {
        "name": "Smart ForTwo BMS Amps",
        "description": "BMS current measurement",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "smart_fortwo",
    },
    "xsq.bms.batt.current": {
        "name": "Smart ForTwo Battery Current",
        "description": "Battery current",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "smart_fortwo",
    },
    "xsq.bms.batt.cv.sum": {
        "name": "Smart ForTwo Battery CV Sum",
        "description": "Sum of cell voltages",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "smart_fortwo",
    },
    "xsq.bms.batt.link.voltage": {
        "name": "Smart ForTwo Battery Link Voltage",
        "description": "Battery link voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "smart_fortwo",
    },
    "xsq.bms.batt.power": {
        "name": "Smart ForTwo Battery Power",
        "description": "Battery power",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPower.KILO_WATT,
        "category": "smart_fortwo",
    },
    "xsq.bms.batt.voltage": {
        "name": "Smart ForTwo Battery Voltage",
        "description": "Battery voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "smart_fortwo",
    },
    "xsq.bms.cv.range.max": {
        "name": "Smart ForTwo Cell Voltage Max",
        "description": "Maximum cell voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "smart_fortwo",
    },
    "xsq.bms.cv.range.mean": {
        "name": "Smart ForTwo Cell Voltage Mean",
        "description": "Mean cell voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "smart_fortwo",
    },
    "xsq.bms.cv.range.min": {
        "name": "Smart ForTwo Cell Voltage Min",
        "description": "Minimum cell voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "smart_fortwo",
    },
    "xsq.bms.ev.mode": {
        "name": "Smart ForTwo EV Mode",
        "description": "EV operation mode",
        "icon": "mdi:car-electric",
        "category": "smart_fortwo",
    },
    "xsq.bms.hv": {
        "name": "Smart ForTwo High Voltage",
        "description": "High voltage measurement",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "smart_fortwo",
    },
    "xsq.bms.hv.contact.state": {
        "name": "Smart ForTwo HV Contact State",
        "description": "High voltage contact state",
        "icon": "mdi:flash",
        "category": "smart_fortwo",
    },
    "xsq.bms.lv": {
        "name": "Smart ForTwo Low Voltage",
        "description": "Low voltage (12V) measurement",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "smart_fortwo",
    },
    "xsq.bms.power": {
        "name": "Smart ForTwo BMS Power",
        "description": "BMS power measurement",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPower.KILO_WATT,
        "category": "smart_fortwo",
    },
    "xsq.booster.1to3": {
        "name": "Smart ForTwo Booster 1to3",
        "description": "Booster parameter 1to3",
        "icon": "mdi:speedometer",
        "category": "smart_fortwo",
    },
    "xsq.booster.data": {
        "name": "Smart ForTwo Booster Data",
        "description": "Booster data parameters",
        "icon": "mdi:chart-bar",
        "category": "smart_fortwo",
    },
    "xsq.booster.de": {
        "name": "Smart ForTwo Booster DE",
        "description": "Booster DE parameter",
        "icon": "mdi:gauge",
        "category": "smart_fortwo",
    },
    "xsq.booster.ds": {
        "name": "Smart ForTwo Booster DS",
        "description": "Booster DS parameter",
        "icon": "mdi:gauge",
        "category": "smart_fortwo",
    },
    "xsq.booster.h": {
        "name": "Smart ForTwo Booster Hour",
        "description": "Booster hour setting",
        "icon": "mdi:clock",
        "category": "smart_fortwo",
    },
    "xsq.booster.m": {
        "name": "Smart ForTwo Booster Minute",
        "description": "Booster minute setting",
        "icon": "mdi:clock",
        "category": "smart_fortwo",
    },
    "xsq.booster.on": {
        "name": "Smart ForTwo Booster Active",
        "description": "Booster active state",
        "icon": "mdi:power",
        "device_class": BinarySensorDeviceClass.POWER,
        "category": "smart_fortwo",
    },
    "xsq.booster.time": {
        "name": "Smart ForTwo Booster Time",
        "description": "Booster time setting",
        "icon": "mdi:clock",
        "category": "smart_fortwo",
    },
    "xsq.booster.weekly": {
        "name": "Smart ForTwo Booster Weekly",
        "description": "Booster weekly schedule active",
        "icon": "mdi:calendar-clock",
        "device_class": BinarySensorDeviceClass.RUNNING,
        "category": "smart_fortwo",
    },
    "xsq.evc.ext.power": {
        "name": "Smart ForTwo External Power",
        "description": "External power connected",
        "icon": "mdi:power-plug",
        "device_class": BinarySensorDeviceClass.PLUG,
        "category": "smart_fortwo",
    },
    "xsq.evc.hv.energy": {
        "name": "Smart ForTwo HV Energy",
        "description": "High voltage energy measurement",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "smart_fortwo",
    },
    "xsq.evc.lv.dcdc.amps": {
        "name": "Smart ForTwo DCDC Amps",
        "description": "DC-DC converter current",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "smart_fortwo",
    },
    "xsq.evc.lv.dcdc.load": {
        "name": "Smart ForTwo DCDC Load",
        "description": "DC-DC converter load percentage",
        "icon": "mdi:gauge",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "smart_fortwo",
    },
    "xsq.evc.lv.dcdc.power": {
        "name": "Smart ForTwo DCDC Power",
        "description": "DC-DC converter power",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPower.KILO_WATT,
        "category": "smart_fortwo",
    },
    "xsq.evc.lv.dcdc.state": {
        "name": "Smart ForTwo DCDC State",
        "description": "DC-DC converter state",
        "icon": "mdi:power",
        "category": "smart_fortwo",
    },
    "xsq.evc.lv.dcdc.volt": {
        "name": "Smart ForTwo DCDC Voltage",
        "description": "DC-DC converter voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "smart_fortwo",
    },
    "xsq.evc.plug.present": {
        "name": "Smart ForTwo Plug Connected",
        "description": "Charge plug connection status",
        "icon": "mdi:power-plug",
        "device_class": BinarySensorDeviceClass.PLUG,
        "category": "smart_fortwo",
    },
    "xsq.obl.amps": {
        "name": "Smart ForTwo Charger Amps",
        "description": "Charger current measurements",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "smart_fortwo",
    },
    "xsq.obl.fastchg": {
        "name": "Smart ForTwo Fast Charging",
        "description": "Fast charging active",
        "icon": "mdi:ev-station",
        "device_class": BinarySensorDeviceClass.BATTERY_CHARGING,
        "category": "smart_fortwo",
    },
    "xsq.obl.freq": {
        "name": "Smart ForTwo Charger Frequency",
        "description": "Charger frequency",
        "icon": "mdi:sine-wave",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "smart_fortwo",
    },
    "xsq.obl.power": {
        "name": "Smart ForTwo Charger Power",
        "description": "Charger power measurement",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPower.KILO_WATT,
        "category": "smart_fortwo",
    },
    "xsq.obl.volts": {
        "name": "Smart ForTwo Charger Volts",
        "description": "Charger voltage measurements",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "smart_fortwo",
    },
    "xsq.ocs.duration": {
        "name": "Smart ForTwo OCS Duration",
        "description": "OCS duration",
        "icon": "mdi:timer",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTime.MINUTES,
        "category": "smart_fortwo",
    },
    "xsq.ocs.mt.day.prewarn": {
        "name": "Smart ForTwo Maintenance Prewarn Days",
        "description": "Days before maintenance prewarn",
        "icon": "mdi:wrench-clock",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTime.DAYS,
        "category": "smart_fortwo",
    },
    "xsq.ocs.mt.day.usual": {
        "name": "Smart ForTwo Maintenance Days",
        "description": "Days until next scheduled maintenance",
        "icon": "mdi:wrench-clock",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTime.DAYS,
        "category": "smart_fortwo",
    },
    "xsq.ocs.mt.km.usual": {
        "name": "Smart ForTwo Maintenance Distance",
        "description": "Distance until next scheduled maintenance",
        "icon": "mdi:wrench",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfLength.METERS,
        "category": "smart_fortwo",
    },
    "xsq.ocs.mt.level": {
        "name": "Smart ForTwo Maintenance Level",
        "description": "Maintenance service level required",
        "icon": "mdi:wrench",
        "category": "smart_fortwo",
    },
    "xsq.ocs.trip.km": {
        "name": "Smart ForTwo Trip Distance",
        "description": "Trip distance in km",
        "icon": "mdi:map-marker-distance",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfLength.METERS,
        "category": "smart_fortwo",
    },
    "xsq.ocs.trip.time": {
        "name": "Smart ForTwo Trip Time",
        "description": "Trip time in hours:minutes",
        "icon": "mdi:clock",
        "category": "smart_fortwo",
    },
    "xsq.odometer.start": {
        "name": "Smart ForTwo Odometer Start",
        "description": "Odometer at start",
        "icon": "mdi:counter",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfLength.METERS,
        "category": "smart_fortwo",
    },
    "xsq.odometer.start.total": {
        "name": "Smart ForTwo Odometer Start Total",
        "description": "Total odometer at start",
        "icon": "mdi:counter",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfLength.METERS,
        "category": "smart_fortwo",
    },
    "xsq.odometer.trip.total": {
        "name": "Smart ForTwo Odometer Trip Total",
        "description": "Total trip distance",
        "icon": "mdi:counter",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfLength.METERS,
        "category": "smart_fortwo",
    },
    "xsq.use.at.reset": {
        "name": "Smart ForTwo Energy At Reset",
        "description": "Energy usage at reset",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "smart_fortwo",
    },
    "xsq.v.bms.temps": {
        "name": "Smart ForTwo BMS Temperatures",
        "description": "BMS temperature readings",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "smart_fortwo",
    },
    "xsq.v.bus.awake": {
        "name": "Smart ForTwo Bus Awake",
        "description": "Vehicle bus awake status",
        "icon": "mdi:power",
        "device_class": BinarySensorDeviceClass.POWER,
        "category": "smart_fortwo",
    },
}
