"""VW e-UP specific metrics for OVMS integration."""

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)
from homeassistant.components.binary_sensor import (
    BinarySensorDeviceClass,
)
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfLength,  # noqa: F401
    UnitOfPower,
    UnitOfTemperature,  # noqa: F401
    UnitOfTime,
    UnitOfPressure,
    EntityCategory,
)

# Custom unit constants
UNIT_AMPERE_HOUR = "Ah"

# VW e-UP specific metrics
VW_EUP_METRICS = {
    "xvu.b.cap.ah.abs": {
        "name": "VW eUP! Absolute Battery Capacity",
        "description": "Absolute battery capacity",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY_STORAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,  # Changed from UNIT_AMPERE_HOUR to kWh
        "category": "vw_eup",
    },
    "xvu.b.cap.ah.norm": {
        "name": "VW eUP! Normalized Battery Capacity",
        "description": "Normalized battery capacity",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY_STORAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,  # Changed from UNIT_AMPERE_HOUR to kWh
        "category": "vw_eup",
    },
    "xvu.b.cap.kwh.abs": {
        "name": "VW eUP! Absolute Battery Energy",
        "description": "Absolute battery capacity in kWh",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY_STORAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "vw_eup",
    },
    "xvu.b.cap.kwh.norm": {
        "name": "VW eUP! Normalized Battery Energy",
        "description": "Normalized battery capacity in kWh",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY_STORAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "vw_eup",
    },
    "xvu.b.cap.kwh.range": {
        "name": "VW eUP! Range Battery Energy",
        "description": "Battery capacity available for range in kWh",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY_STORAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "vw_eup",
    },
    "xvu.b.cell.delta": {
        "name": "VW eUP! Cell Voltage Delta",
        "description": "Maximum voltage difference between cells",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "vw_eup",
    },
    "xvu.b.energy.range": {
        "name": "VW eUP! Energy Available for Range",
        "description": "Energy available for driving range",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,  # Changed from MEASUREMENT to TOTAL
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "vw_eup",
    },
    "xvu.b.soc.abs": {
        "name": "VW eUP! Absolute SOC",
        "description": "Absolute state of charge",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "vw_eup",
    },
    "xvu.b.soh.charge": {
        "name": "VW eUP! SOH Charge",
        "description": "State of health based on charge capacity",
        "icon": "mdi:battery-heart",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "vw_eup",
    },
    "xvu.b.soh.range": {
        "name": "VW eUP! SOH Range",
        "description": "State of health based on range capacity",
        "icon": "mdi:battery-heart",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "vw_eup",
    },
    "xvu.b.soh.vw": {
        "name": "VW eUP! SOH VW",
        "description": "State of health reported by VW",
        "icon": "mdi:battery-heart",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "vw_eup",
    },
    "xvu.c.ac.i1": {
        "name": "VW eUP! AC Charging Current L1",
        "description": "AC charging current phase 1",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "vw_eup",
    },
    "xvu.c.ac.i2": {
        "name": "VW eUP! AC Charging Current L2",
        "description": "AC charging current phase 2",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "vw_eup",
    },
    "xvu.c.ac.p": {
        "name": "VW eUP! AC Charging Power",
        "description": "AC charging power",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPower.KILO_WATT,
        "category": "vw_eup",
    },
    "xvu.c.ac.u1": {
        "name": "VW eUP! AC Charging Voltage L1",
        "description": "AC charging voltage phase 1",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "vw_eup",
    },
    "xvu.c.ac.u2": {
        "name": "VW eUP! AC Charging Voltage L2",
        "description": "AC charging voltage phase 2",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "vw_eup",
    },
    "xvu.c.ccs.i": {
        "name": "VW eUP! DC Charging Current",
        "description": "CCS DC charging current",
        "icon": "mdi:current-dc",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "vw_eup",
    },
    "xvu.c.ccs.p": {
        "name": "VW eUP! DC Charging Power",
        "description": "CCS DC charging power",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPower.KILO_WATT,
        "category": "vw_eup",
    },
    "xvu.c.ccs.u": {
        "name": "VW eUP! DC Charging Voltage",
        "description": "CCS DC charging voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "vw_eup",
    },
    "xvu.c.dc.i1": {
        "name": "VW eUP! DC-DC Input Current",
        "description": "DC-DC converter input current",
        "icon": "mdi:current-dc",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "vw_eup",
    },
    "xvu.c.dc.i2": {
        "name": "VW eUP! DC-DC Output Current",
        "description": "DC-DC converter output current",
        "icon": "mdi:current-dc",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "vw_eup",
    },
    "xvu.c.dc.p": {
        "name": "VW eUP! DC-DC Power",
        "description": "DC-DC converter power",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPower.KILO_WATT,
        "category": "vw_eup",
    },
    "xvu.c.dc.u1": {
        "name": "VW eUP! DC-DC Input Voltage",
        "description": "DC-DC converter input voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "vw_eup",
    },
    "xvu.c.dc.u2": {
        "name": "VW eUP! DC-DC Output Voltage",
        "description": "DC-DC converter output voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "vw_eup",
    },
    "xvu.c.eff.calc": {
        "name": "VW eUP! Charging Efficiency Calculated",
        "description": "Calculated charging efficiency",
        "icon": "mdi:battery-charging",
        "device_class": SensorDeviceClass.POWER_FACTOR,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "vw_eup",
    },
    "xvu.c.eff.ecu": {
        "name": "VW eUP! Charging Efficiency ECU",
        "description": "ECU reported charging efficiency",
        "icon": "mdi:battery-charging",
        "device_class": SensorDeviceClass.POWER_FACTOR,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "vw_eup",
    },
    "xvu.c.limit.soc.max": {
        "name": "VW eUP! Max SOC Limit",
        "description": "Maximum SOC limit for charging",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "vw_eup",
    },
    "xvu.c.limit.soc.min": {
        "name": "VW eUP! Min SOC Limit",
        "description": "Minimum SOC limit for charging",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "vw_eup",
    },
    "xvu.c.loss.calc": {
        "name": "VW eUP! Calculated Charging Loss",
        "description": "Calculated power loss during charging",
        "icon": "mdi:flash-off",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPower.KILO_WATT,
        "category": "vw_eup",
    },
    "xvu.c.loss.ecu": {
        "name": "VW eUP! ECU Charging Loss",
        "description": "ECU reported power loss during charging",
        "icon": "mdi:flash-off",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPower.KILO_WATT,
        "category": "vw_eup",
    },
    "xvu.c.soc.norm": {
        "name": "VW eUP! Normalized SOC",
        "description": "Normalized state of charge",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "vw_eup",
    },
    "xvu.c.timermode.def": {
        "name": "VW eUP! Default Timer Mode",
        "description": "Default timer mode enabled state",
        "icon": "mdi:timer",
        "device_class": BinarySensorDeviceClass.RUNNING,
        "category": "vw_eup",
    },
    "xvu.e.hv.chgmode": {
        "name": "VW eUP! HV Charging Mode",
        "description": "High voltage charging mode",
        "icon": "mdi:battery-charging",
        "category": "vw_eup",
    },
    "xvu.e.lv.autochg": {
        "name": "VW eUP! 12V Auto Charging",
        "description": "12V automatic charging enabled",
        "icon": "mdi:battery-charging",
        "device_class": BinarySensorDeviceClass.BATTERY_CHARGING,
        "category": "vw_eup",
    },
    "xvu.e.lv.pwrstate": {
        "name": "VW eUP! LV Power State",
        "description": "Low voltage power state",
        "icon": "mdi:power-settings",
        "category": "vw_eup",
    },
    "xvu.e.serv.days": {
        "name": "VW eUP! Service Days",
        "description": "Days until next service",
        "icon": "mdi:wrench-clock",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTime.DAYS,
        "category": "vw_eup",
    },
    "xvu.m.soc.abs": {
        "name": "VW eUP! Motor Controller Absolute SOC",
        "description": "Motor controller absolute state of charge",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "vw_eup",
    },
    "xvu.m.soc.norm": {
        "name": "VW eUP! Motor Controller Normalized SOC",
        "description": "Motor controller normalized state of charge",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "vw_eup",
    },
    "xvu.m.version": {
        "name": "VW eUP! Module Version",
        "description": "eUP module software version",
        "icon": "mdi:tag-text",
        "category": "vw_eup",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "xvu.v.t.diff": {
        "name": "VW eUP! Tire Pressure Difference",
        "description": "Difference in tire pressure values",
        "icon": "mdi:car-tire-alert",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPressure.KPA,
        "category": "vw_eup",
        "has_cell_data": True,
    },
    "xvu.v.t.emgcy": {
        "name": "VW eUP! Tire Emergency Values",
        "description": "Emergency tire pressure values",
        "icon": "mdi:car-tire-alert",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPressure.KPA,
        "category": "vw_eup",
        "has_cell_data": True,
    },
}
