"""Topic patterns for OVMS integration metrics."""

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)
from homeassistant.components.binary_sensor import (
    BinarySensorDeviceClass,
)
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfLength,
    UnitOfPower,
    UnitOfPressure,
    UnitOfSpeed,
    UnitOfTemperature,
    UnitOfFrequency,
    UnitOfTime,
)
from homeassistant.helpers.entity import EntityCategory

# Simplified mapping for lookup by keyword/pattern
TOPIC_PATTERNS = {
    "soc": {
        "name": "Battery State of Charge",
        "icon": "mdi:battery",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": PERCENTAGE,
        "category": "battery",
    },
    "range": {
        "name": "Range",
        "icon": "mdi:map-marker-distance",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfLength.KILOMETERS,
        "category": "battery",
    },
    "temp": {
        "name": "Temperature",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "climate",
    },
    # Also match "temperature" for consistency with SENSOR_TYPES
    "temperature": {
        "name": "Temperature",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "climate",
    },
    "voltage": {
        "name": "Voltage",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricPotential.VOLT,
        "category": "battery",
    },
    "current": {
        "name": "Current",
        "icon": "mdi:current-ac",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfElectricCurrent.AMPERE,
        "category": "battery",
    },
    "power": {
        "name": "Power",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPower.WATT,
        "category": "power",
    },
    "energy": {
        "name": "Energy",
        "icon": "mdi:flash",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "category": "battery",
    },
    "speed": {
        "name": "Speed",
        "icon": "mdi:speedometer",
        "device_class": SensorDeviceClass.SPEED,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfSpeed.KILOMETERS_PER_HOUR,
        "category": "trip",
    },
    "odometer": {
        "name": "Odometer",
        "icon": "mdi:counter",
        "device_class": SensorDeviceClass.DISTANCE,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "unit": UnitOfLength.KILOMETERS,
        "category": "trip",
    },
    "pressure": {
        "name": "Pressure",
        "icon": "mdi:gauge",
        "device_class": SensorDeviceClass.PRESSURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPressure.KPA,
        "category": "tire",
    },
    "signal": {
        "name": "Signal Strength",
        "icon": "mdi:signal",
        "device_class": SensorDeviceClass.SIGNAL_STRENGTH,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": "dBm",
        "category": "network",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "door": {
        "name": "Door",
        "icon": "mdi:car-door",
        "device_class": BinarySensorDeviceClass.DOOR,
        "category": "door",
    },
    "lock": {
        "name": "Lock",
        "icon": "mdi:lock",
        "device_class": BinarySensorDeviceClass.LOCK,
        "category": "door",
    },
    "charging": {
        "name": "Charging",
        "icon": "mdi:battery-charging",
        "device_class": BinarySensorDeviceClass.BATTERY_CHARGING,
        "category": "charging",
    },
    "climate": {
        "name": "Climate Control",
        "icon": "mdi:air-conditioner",
        "category": "climate",
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "fan": {
        "name": "Fan",
        "icon": "mdi:fan",
        "category": "climate",
    },
    "trunk": {
        "name": "Trunk",
        "icon": "mdi:car-back",
        "device_class": BinarySensorDeviceClass.DOOR,
        "category": "door",
    },
    "hood": {
        "name": "Hood",
        "icon": "mdi:car-lifted-pickup",
        "device_class": BinarySensorDeviceClass.DOOR,
        "category": "door",
    },
    "timer": {
        "name": "Timer",
        "icon": "mdi:timer",
        "device_class": SensorDeviceClass.DURATION,
        "unit": UnitOfTime.SECONDS,
        "category": "system",
    },
    "version": {
        "name": "Version",
        "icon": "mdi:package-up",
        "category": "system",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "status": {
        "name": "Status",
        "icon": "mdi:information-outline",
        "category": "system",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "alert": {
        "name": "Alert",
        "icon": "mdi:alert",
        "device_class": BinarySensorDeviceClass.PROBLEM,
        "category": "diagnostic",
    },
    # Vehicle-specific patterns
    "xvu": {
        "name": "VW eUP!",
        "icon": "mdi:car-electric",
        "category": "vw_eup",
    },
    "xsq": {
        "name": "Smart ForTwo",
        "icon": "mdi:car-electric",
        "category": "smart_fortwo",
    },
    "xmg": {
        "name": "MG ZS-EV",
        "icon": "mdi:car-electric",
        "category": "mg_zs_ev",
    },
    "xnl": {
        "name": "Nissan Leaf",
        "icon": "mdi:car-electric",
        "category": "nissan_leaf",
    },
    # Custom patterns
    "egpio_input": {
        "name": "GPIO Input Ports",
        "icon": "mdi:integrated-circuit-chip",
        "category": "system",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "egpio_output": {
        "name": "GPIO Output Ports",
        "icon": "mdi:integrated-circuit-chip",
        "category": "system",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "t_diff": {
        "name": "Tire Pressure Difference",
        "icon": "mdi:car-tire-alert",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPressure.KPA,
        "category": "tire",
    },
    "diff": {
        "name": "Difference",
        "icon": "mdi:car-tire-alert",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfPressure.KPA,
        "category": "tire",
    },
    "frequency": {
        "name": "Frequency",
        "icon": "mdi:sine-wave",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfFrequency.HERTZ,
        "category": "system",
    },
    "torque": {
        "name": "Torque",
        "icon": "mdi:gauge",
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": "Nm",
        "category": "motor",
    },
    "coolant": {
        "name": "Coolant Temperature",
        "icon": "mdi:thermometer",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTemperature.CELSIUS,
        "category": "climate",
    },
    "resistance": {
        "name": "Resistance",
        "icon": "mdi:resistor",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "battery",
    },
    "dcdc": {
        "name": "DC-DC Converter",
        "icon": "mdi:car-battery",
        "category": "power",
    },
    "gids": {
        "name": "GIDs",
        "icon": "mdi:battery-medium",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "nissan_leaf",
    },
    "balancing": {
        "name": "Cell Balancing",
        "icon": "mdi:battery-sync",
        "category": "nissan_leaf",
    },
    "thermistor": {
        "name": "Thermistor",
        "icon": "mdi:thermometer",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "nissan_leaf",
    },
    "hx": {
        "name": "Heat Exchange",
        "icon": "mdi:heat-wave",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "nissan_leaf",
    },
    "chargebars": {
        "name": "Charge Bars",
        "icon": "mdi:battery-charging",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "nissan_leaf",
    },
    # New additions from SENSOR_TYPES
    "efficiency": {
        "name": "Efficiency",
        "icon": "mdi:leaf",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "battery",
    },
    "charging_time": {
        "name": "Charging Time",
        "icon": "mdi:timer",
        "state_class": SensorStateClass.MEASUREMENT,
        "device_class": SensorDeviceClass.DURATION,
        "unit": UnitOfTime.SECONDS,
        "category": "charging",
    },
    "parktime": {
        "name": "Park Time",
        "icon": "mdi:timer",
        "state_class": SensorStateClass.MEASUREMENT,
        "device_class": SensorDeviceClass.DURATION,
        "unit": UnitOfTime.SECONDS,
        "category": "trip",
    },
    "hvac": {
        "name": "HVAC",
        "icon": "mdi:air-conditioner",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "climate",
    },
    "motor": {
        "name": "Motor",
        "icon": "mdi:engine",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "motor",
    },
    "trip": {
        "name": "Trip",
        "icon": "mdi:map-marker-path",
        "state_class": SensorStateClass.MEASUREMENT,
        "category": "trip",
    },
    "firmware": {
        "name": "Firmware",
        "icon": "mdi:package-up",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "category": "system",
    },
    "task": {
        "name": "Task",
        "icon": "mdi:list-status",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "category": "system",
    },
    "duration": {
        "name": "Duration",
        "icon": "mdi:timer-outline",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.MEASUREMENT,
        "unit": UnitOfTime.SECONDS,
        "category": "system",
    },
}
